config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get  "account", to: "account#account"

  resources :businesses, only: [] do
    resource :saved, only: [ :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business.rb
class Business < ApplicationRecord
    has_many :saveds, dependent: :destroy
    has_many :saved_by_users, through: :saveds, source: :user

    has_many :reviews, dependent: :destroy

    has_many :recently_searched_businesses, dependent: :destroy
    has_many :recently_searches, through: :recently_searched_businesses

    def self.search(params, user = nil)
        # Rails.logger.warn("testing ----")
        return [] if params.empty?

        businesses = Business.all
        for param in params
          if param[:services].present?
            businesses = businesses.and(Business.where(
                "services LIKE '%#{param[:services]}%'"
            ))
          else
            businesses = businesses.and(Business.where(param))
          end
        end

        if user
          businesses = businesses
                        .left_joins(:saveds)
                        .left_joins(:reviews)
                        .where("saveds.user_id = ? OR saveds.user_id IS NULL", user[:id])
                        .where("reviews.user_id = ? OR reviews.user_id IS NULL", user[:id])
                        .select("businesses.*, CASE WHEN saveds.id IS NULL THEN FALSE ELSE TRUE END AS saved, reviews.id AS review_id, reviews.score AS review_score, reviews.comments AS review_comments")
        end

        businesses.distinct
    end

    def saved_by?(user)
      return false unless user
      saved_by_users.loaded? ?
        saved_by_users.any? { |u| u.id == user.id } :
        saveds.exists?(user_id: user.id)
    end

    def user_review
      return nil unless self[:review_id]

      {
        id: self[:review_id],
        score: self[:review_score],
        comments: self[:review_comments]
      }
    end
end

app/models/recent_search.rb
class RecentSearch < ApplicationRecord
  MAX_PER_USER = 3

  belongs_to :user
  has_many :recently_searched_businesses, dependent: :destroy
  has_many :businesses, through: :recently_searched_businesses

  default_scope { order(last_query_date: :desc) }
  after_commit :enforce_limit, on: :create

  private

  def enforce_limit
    oldSearches = user.recent_searches.offset(MAX_PER_USER)
    oldSearches.destroy_all if oldSearches.exists?
  end
end

app/models/recently_searched_business.rb
class RecentlySearchedBusiness < ApplicationRecord
  belongs_to :recent_search
  belongs_to :business
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :business

  before_validation :normalize_score
  validates :score, presence: true, numericality: true, inclusion: { in: 0.0..5.0 }

  private
  def normalize_score
    return if score.nil?

    self.score = score.to_f.round(1)
  end
end

app/models/saved.rb
class Saved < ApplicationRecord
  belongs_to :user
  belongs_to :business
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :saveds, dependent: :destroy
  has_many :saved_businesses, through: :saveds, source: :business

  has_many :reviews, dependent: :destroy

  has_many :recent_searches, dependent: :destroy
  has_many :recently_searched_businesses, through: :recent_searches
  has_many :recently_viewed_businesses, through: :recently_searched_businesses, source: :business
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
    before_action :authenticate_user!

    def account
        @recent_searches = current_user.recent_searches.includes(:businesses).order(last_query_date: :desc).limit(3)
        @saved_businesses = current_user.saved_businesses
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    city = params[:city]
    service = params[:service]

    search_args = []
    if !city.blank?
      search_args << { location: city }
    end
    if !service.blank?
      search_args << { services: service }
    end

    @businesses = Business.search(search_args, current_user)


    if current_user && search_args.any?
      recent_search = RecentSearch.create!(
        user: current_user,
        city: city,
        service: service,
        last_query_date: Time.current
      )

      recent_search.businesses << @businesses
      Rails.logger.warn("recent search: ")
      Rails.logger.warn(recent_search)
    end
  end

  def show
    # cant use Business.seacrh, because it returns an array
    # business = Business.find(id)
    #
    # Business.search() -> [buinsses1, etc]
    # business = businesses[0], only expect one business to be returned, because you search by id (unique)
    # Business.find()
    # Business.where() returns array
    # don't have access to Business.saved?
    # if you want access, you have to write another custom search, that returns one Business with the saved property
  end
end

app/controllers/saveds_controller.rb
class SavedsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_business

  def create
    current_user.saveds.find_or_create_by!(business: @business)
    render_business
  end

  def destroy
    current_user.saveds.where(business: @business).destroy_all
    render_business
  end

  private

  def set_business
    @business = Business.find(params[:business_id])
  end

  def render_business
    frame_id = request.headers["Turbo-Frame"]
    Rails.logger.warn("this is the frame id: #{frame_id}")
    context = frame_id&.split("_business_")&.first || "default"

    business = Business.left_joins(:saveds)
                        .where("businesses.id = ?", @business.id)
                        .where("saveds.user_id = ? OR saveds.user_id IS NULL", current_user.id)
                        .select(
                         "businesses.*, CASE WHEN saveds.user_id IS NULL THEN FALSE ELSE TRUE END AS saved"
                       ).first

    render turbo_stream: turbo_stream.replace(
      "#{context}_business_#{@business.id}",
      partial: "home/business",
      locals: { business: business, show_saved: true, context: context }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_alerts.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissable fade show mt-3" role="alert">
        <%= value %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/home/_business.html.erb
<%= turbo_frame_tag dom_id(business, context) do %>
  <div class="business-row">
    <div class="business-col name">
      <h3><%= business.name %></h3>
    </div>

    <div class="business-col">
      <span class="label">Location</span>
      <span><%= business.location %></span>
    </div>

    <div class="business-col">
      <span class="label">Services</span>
      <span><%= business.services %></span>
    </div>

    <div class="business-col link">
      <a href="<%= business.website %>" target="_blank">Website ↗</a>
    </div>

    <% if show_saved && user_signed_in? %>
    <div class="business-col actions">
        <% if business.saved_by?(current_user) %>
          <%= button_to "★ Saved",
                business_saved_path(business),
                method: :delete,
                form: { data: { turbo_frame: dom_id(business, context) } },
                class: "saved-btn active" %>
        <% else %>
          <%= button_to "☆ Save",
                business_saved_path(business),
                method: :post,
                form: { data: { turbo_frame: dom_id(business, context) } },
                class: "saved-btn" %>
        <% end %>        
    </div>
    <% end %>
  </div>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
    <%= link_to 'FitMap', root_path, class:"navbar-brand" %>
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <% if !user_signed_in? %>
                    <%= link_to 'Log In', new_user_session_path, class:"nav-link" %>
                    <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
                <% else %>
                    <%= link_to 'Account', account_path, class:"nav-link active", "aria-current": "page" %>
                    <%= link_to "Log Out", destroy_user_session_path,
                        data: { turbo_method: :delete },
                        class: "nav-link" %>
                <% end %>
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<h1>Find Gyms, Studios, Fitness Centers, and more!</h1>

<div class="search-container">
  <form class="search-bar" action="/" method="get">

    <div class="search-field">
      <input
        type="text"
        name="city"
        placeholder="City"/>
      <span class="icon">▾</span>
    </div>

    <div class="search-field">
      <input
        type="text"
        name="service"
        placeholder="Services"/>
      <span class="icon">×</span>
    </div>

    <div class="search-field">
      <input
        type="text"
        name="country"
        placeholder="🇨🇦 Canada"
      />
      <span class="icon">▾</span>
    </div>

    <button type="submit" class="search-button">
      🔍
    </button>

  </form>
</div>

<div class="results-list">
  <% @businesses.each do |business| %> 
      <%= render "home/business", 
        business: business, 
        show_saved: true,
        context: :search %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FitMap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Fit Map">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%=render "home/header" %>
    <%=render "home/alerts" %>
    
    <div class="container">
      <br></br>
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    </div>
  </body>
</html>